### ISSUE TITLE
When a hyperlink is opened, it cannot go back

### ISSUE THREAD

**Issue by ladyrick** [harmsk/atom-html-preview#114]
Like this:

``` html
<html>
    <body>
        <a href="github.com">test</a>
    </body>
</html>
```

When I press the hyperlink in the preview window, it comes to a empty page, and it cannot go back by pressing F5.
I have to reopen the preview window to go back to the original html page.

**Comment by jord8on** [comment]
I'm having the same issue. It would be nice if there were a "back" shortcut key that we could use.
