### ISSUE TITLE
doesn't Work on Mac

### ISSUE THREAD

**Issue by semk01** [harmsk/atom-html-preview#178]
I also downloaded it and i found out that it doesn't work on mac. I think its because the ctrl in mac is cmd. like: ctrl +v on windows is cmd+v on mac. So now it doesn't work.

**Comment by danehendren** [comment]
any solution to this? also just found this out.

**Comment by semk01** [comment]
Yeah its me again, after pressing cmd+shift+p i found out that if you press ctrl+shift+m (or fn+shift+m or alt+shift+m don't know for sure just try these 3) it will work.
