### ISSUE TITLE
Showing a white blank page

### ISSUE THREAD

**Issue by maya-66** [harmsk/atom-html-preview#201]
It doesn't work on windows 10. I tried on both x86 and x64 version of atom. also I installed previous versions of html preview but still doesn't work and just showing a white blank page.

![untitled](https://user-images.githubusercontent.com/47255149/52142490-66f94f80-261e-11e9-9191-d5c294138cf4.jpg)

Atom 1.34.0 x64
atom-html-preview 0.2.6
Windows 10

**Comment by doost8** [comment]
I have the same issue

**Comment by BradHeff** [comment]
same issue here too.

**Comment by doost8** [comment]
If you save the file as a .html and then quit and re-open it should work. That fixed it for me, it needs to know it's loading a .html file.

**Comment by romain-dartigues** [comment]
# Description

Same symptoms as OP.
Maybe related to #202 and #206.

## Steps to Reproduce

1. create a file with a minimalist content (ex.: `Hello World!`)
2. name the file `foo#bar.html`
3. open the file in Atom, trigger HTML preview → this leads to a blank page

The HTML preview **does** work when renaming the file `foo bar.html`.

## Platform

- ATOM: 1.41.0 x64
- Electron: 4.2.7
- Chrome: 69.0.3497.128
- Node: v10.11.0
- atom-html-preview: 0.2.6
- OS: Linux Mint 19.2 Tina

**Comment by MotsyRobotsy1984** [comment]
I'm having the same issue, except the Preview panel displays a blank white background and then changes to black. I'm using the latest version of Atom (1.45.0 x64) on a Mac running OS Mojave.
<img width="2560" alt="Screenshot 2020-03-13 at 11 29 08" src="https://user-images.githubusercontent.com/60971168/76617268-de85f780-651d-11ea-88e3-5fd3398fc3ce.png">

**Comment by Halmeth** [comment]
> I'm having the same issue, except the Preview panel displays a blank white background and then changes to black. I'm using the latest version of Atom (1.45.0 x64) on a Mac running OS Mojave.
> 
> <img alt="Screenshot 2020-03-13 at 11 29 08" width="2000" src="https://user-images.githubusercontent.com/60971168/76617268-de85f780-651d-11ea-88e3-5fd3398fc3ce.png">

Hey!

I have the same issue! After upgrading to ATOM 1.45 I have the same problem.

Did you solved it yet?

**Comment by MotsyRobotsy1984** [comment]
No, I've not managed to fix the issue. Can anyone give us some advice?

**Comment by harmsk** [comment]
Must set the current file's grammar to HTML.
