### ISSUE TITLE
preview panel not opening

### ISSUE THREAD

**Issue by sushdg** [harmsk/atom-html-preview#212]

**Comment by pannannanna** [comment]
Same, I did a fresh install of both atom and the preview package with no luck. The shortcut has no effect on it either

**Comment by sushdg** [comment]
Yeah did the same thing! Should we install some preview tool?

**Comment by danleetc** [comment]
My preview has stopped working this morning when I tried to resume some  coding. The preview package was working just 5 hours ago. Not sure what has changed overnight....

**Comment by aubreyz** [comment]
Related https://github.com/harmsk/atom-html-preview/issues/208

Package not working until updated to work with current javascript packages

**Comment by josiah854** [comment]
> Related #208
> 
> Package not working until updated to work with current javascript packages

How and which javascript package do I update?

**Comment by dechen477** [comment]
mine also preview is not working at all,, why does it happening so?

**Comment by harmsk** [comment]
duplicate of #214
