### ISSUE TITLE
atom-hteml-preview not opening

### ISSUE THREAD

**Issue by plai1** [harmsk/atom-html-preview#213]
This is my first-day using atom and I want a preview of what my code will look like in a website view in HTML. I found out about this package online and it was the most popular downloaded package I could find. Right now, I can't open the panel through both methods (key bindings or through the package tab) and I need to see how I'm doing. Please fix this issue as soon as possible

**Comment by aubreyz** [comment]
Likely related to https://github.com/harmsk/atom-html-preview/issues/208

This is a great package but recently it has not been working (just for a few weeks -- so hold tight and hopefully the coding wizard will fix it)

**Comment by CezaraH** [comment]
Still not working for me.

**Comment by harmsk** [comment]
duplicate of #214
