### ISSUE TITLE
Blank screen on preview (does not work after upgrade to 1.47)

### ISSUE THREAD

**Issue by Highrider15** [harmsk/atom-html-preview#214]
I was using html-preview yesterday and it was working fine. Today when I started writing a few HTML codes and tried to preview it, it shows a black screen.

![issue](https://user-images.githubusercontent.com/65666043/82460736-29e8f300-9ad7-11ea-8cc0-77a508cebfd3.PNG)

No javascript involved. Please respond asap.

**Comment by cohbalshop** [comment]
I couldn't have said it better.  It worked for me yesterday and today all I get is a blackscreen.

**Comment by Serena2766** [comment]
I have the exact same issue here.

**Comment by Highrider15** [comment]
I tried:

(1.)Re-installing HTML-preview.
(2.)Re-installing Atom. (64-bit version)

Nothing seemed to work.

Then I tried installing Atom on another laptop and even there it did not work, so I think this is due to an update or something like that.

**Comment by cohbalshop** [comment]
This looks like a problem with the 1.47.0 release of Atom that was installed automatically (overnight?) on my machine.  I reinstalled 1.45.0 and preview is working again.

**Comment by Highrider15** [comment]
Yep, this seems to be a problem with the latest update of Atom.

**Comment by claireatati** [comment]
how do i reinstall 1.45.0 version

**Comment by Spencer1996** [comment]
I found this issue yesterday, I thought it may be only my personal problem, but this is the problem of updated Atom right now😅

**Comment by Spencer1996** [comment]
> how do i reinstall 1.45.0 version

Remove and reinstall. you can google 1.45.0 version, this is a link for mac: https://mac.filehorse.com/download-atom/14229/change-log/, maybe you can try it

**Comment by harmsk** [comment]
This is a bug in Atom 1.47: https://github.com/atom/atom/issues/20604

Downgrade to 1.46 until this upstream issue is resolved.

**Comment by simongloor** [comment]
The official Atom 1.46 can be found [here](https://github.com/atom/atom/releases/tag/v1.46.0).

**Comment by dechen477** [comment]
I have exact same issue here...….please help what I have to do now?

**Comment by ecsendmail** [comment]
Me too..program works fine on chrome.....please re-instate older version! Gray screen is all I get....even with the simplest programs...I trust you are working as hard as possible on this problem? Thanks

**Comment by rajat7k** [comment]
i have also facing the same issue..... before 1 hour ago all things were  working perfectly but now it's only showing black scene

**Comment by julieconversiondigital** [comment]
Same issue as well, blank screen.

**Comment by dechen477** [comment]
Still not working

**Comment by jstarrfire** [comment]
Same here - also fails in 1.48.0-beta0

**Comment by aubreyz** [comment]
Some questions need to be asked about how the beta testing could possibly have allowed a version 1.47 to be released, when it killed this and other packages used by more than a million atom users... and why it has not been reverted or fixed, now nearly a month and counting. Atom now has no decent HTML preview or markdown preview plus. Really really bad. I really don't want atom to die a death, but this is the way to drive users away.

**Comment by cohbalshop** [comment]
I downloaded a nightly build (1.50n) 3 days ago and found HTML preview to
be working.

**Comment by aubreyz** [comment]
Yes the nightly builds are promising - but is not what new potential users are going to basing their decisions on, nor are most users who need a stable environment able to use these builds.

**Comment by Highrider15** [comment]
HTML preview working in Atom version 1.4.8
