### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by pulkit2012** [harmsk/atom-html-preview#217]
HTML-preview not working...blank screen issue

**Comment by booklin** [comment]
not working in the atom 1.47.0.   Blank

**Comment by YAACOV2008** [comment]
> not working in the atom 1.47.0. Blank
For me as well

**Comment by Atlanta11** [comment]
Blank screen in Atom 1.47.0 x64

**Comment by FtsPixel** [comment]
Blank screen in Atom 1.47.0 x64

**Comment by nogamesense2** [comment]
Blank screen in Atom 1.47.0 x64

**Comment by VisualCreative** [comment]
Me too, blanks screen since yesterday in Atom 1.47.0

**Comment by harmsk** [comment]
duplicate of #214
