### ISSUE TITLE
 atom html preview is not working.

### ISSUE THREAD

**Issue by Harsh-2950** [harmsk/atom-html-preview#233]
I installed atom html preview package. At starting it worked but next day itself it stopped working. Now i am unstalling it but nothing is happening and nor it is disabling. please help me to solve my issue as soon as posie as it is really important.

**Comment by whiskeytangodelta** [comment]
Same exact problem here

**Comment by whiskeytangodelta** [comment]
Save your file as .html in the file name and it should then work

**Comment by abhilashkrishn** [comment]
Same issue. html is not previewing.

**Comment by jxdesign** [comment]
Exact same issue. Disabling/re-installing didn't work, although it worked the very first time. Does anyone support this package any more?

**Comment by margggggg** [comment]
The fix identified by whiskeytangodelta worked - save your file as .html and the preview loads.

**Comment by slashdottir** [comment]
I just installed this package and SHIFT+CTRL+H does nothing.  OSX
