### ISSUE TITLE
Change shortcut from CTRL+p

### ISSUE THREAD

**Issue by drewzh** [harmsk/atom-html-preview#5]
Interferes with the default for quick goto shortcut in Atom.

**Comment by peterOnePageCRM** [comment]
Yes - it's crazy to re map the most used shortcut!

**Comment by everflux** [comment]
Indeed, please to not override default shortcuts of the core editor.

**Comment by nasifmdtanjim** [comment]
Yes, please change it.

**Comment by warpdesign** [comment]
+1
Since preview does nothing if no file is opened, but still eats ctrl-p shortcut, I couldn't open a new file anymore and first thought my Atom installation was broken :)

**Comment by nasifmdtanjim** [comment]
Easy as pie, open your `keymap.cson` file `Keybindings` settings and add this:
'atom-workspace':
  'ctrl-shift-h': 'atom-html-preview:toggle'
  'ctrl-p': 'fuzzy-finder:toggle-file-finder'

**Comment by antono** [comment]
:+1:

**Comment by mattblang** [comment]
+1
